### ISSUE TITLE
Archive this repo (set to read-only)?

### ISSUE THREAD

**Issue by gordonwoodhull** [crossfilter/promisefilter#5]
I think we should archive this repo, as it isn't actively developed.

@esjewett, is that okay?

I will go ahead in about a week if I don't hear from anyone. (This can always be reversed.)

**Comment by esjewett** [comment]
@gordonwoodhull Yes, this is fine with me. Thank you for watching over this, and sorry for my lack of response here.

**Comment by gordonwoodhull** [comment]
Hi Ethan! No problem. As you know, I have also moved onto other things. 

Many thanks to @kum-deepak for taking over crossfilter2 (temporarily, we hope).
